import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

class ScribeAgent:
    """
    기록서기 (Scribe)
    - ARC v2.0 규격 준수 마크다운 노트 생성
    - 옵시디언 Vault 연동 및 파일 저장
    - RAG 최적화 메타데이터 구성
    """
    
    def __init__(self, vault_path: Optional[str] = None):
        self.name = "Scribe"
        self.vault_path = vault_path or "/Users/msn/Desktop/MS_Brain.nosync"
        self.default_folder = "000 System/010 Inbox"
        self.tpl_path = Path(self.vault_path) / "000 System" / "030 Templates" / "ARC_Theology_Note.md"

    def _discover_vault_path(self):
        return "/Users/msn/Desktop/MS_Brain.nosync"

    def create_note(self, data: Dict[str, Any], folder: str = "010 Inbox") -> str:
        """연구 결과를 바탕으로 ARC 규격 노트 생성"""
        title = data.get("title", "Untitled Research")
        content_body = data.get("content", "")
        
        # 메타데이터 구성
        now = datetime.now().strftime("%Y-%m-%d")
        tags = data.get("tags", ["ARC", "Theology"])
        related = data.get("related", [])
        themes = data.get("themes", [])
        references = data.get("references", [])
        
        # YAML Frontmatter 생성
        yaml_lines = [
            "---",
            f'title: "{title}"',
            f'type: "{data.get("type", "concept")}"',
            f"created: {now}",
            f"updated: {now}",
            f"tags: [{', '.join(tags)}]",
            "related: "
        ]
        
        if not related:
            yaml_lines.append('  - "[[100 Theology/Target_Note]]"')
        for rel in related:
            yaml_lines.append(f'  - "{rel}"')
            
        yaml_lines.append(f"themes: [{', '.join(themes)}]")
        yaml_lines.append("references: ")
        
        if not references:
            yaml_lines.append('  - "N/A"')
        for ref in references:
            yaml_lines.append(f'  - "{ref}"')
            
        yaml_lines.append(f'description: "{data.get("description", "Generated by ARC Secretariat")}"')
        yaml_lines.append("---\n")
        
        # 파일 본문 구성
        full_content = "\n".join(yaml_lines) + f"\n# {title}\n\n" + content_body
        
        # 파일 저장
        safe_title = re.sub(r'[\\/*?:"<>|]', "", title)
        file_name = f"{now}-{safe_title}.md"
        target_dir = Path(self.vault_path) / folder
        target_dir.mkdir(parents=True, exist_ok=True)
        
        file_path = target_dir / file_name
        
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(full_content)
            print(f"✅ [{self.name}] 노트 생성 완료: {file_path}")
            return str(file_path)
        except Exception as e:
            print(f"❌ [{self.name}] 노트 생성 오류: {e}")
            return str(e)

if __name__ == "__main__":
    import argparse
    import json
    import sys

    parser = argparse.ArgumentParser(description="ARC Secretariat - Scribe Agent")
    parser.add_argument("--json", type=str, help="JSON string containing note data (title, content, etc.)")
    parser.add_argument("--file", type=str, help="Path to a JSON file containing note data")
    parser.add_argument("--folder", type=str, default="010 Inbox", help="Target folder in vault")
    
    args = parser.parse_args()
    
    scribe = ScribeAgent()
    data = None
    
    if args.json:
        data = json.loads(args.json)
    elif args.file:
        with open(args.file, "r", encoding="utf-8") as f:
            data = json.load(f)
    else:
        # stdin에서 읽기 시도
        if not sys.stdin.isatty():
            data = json.load(sys.stdin)
            
    if data:
        result_path = scribe.create_note(data, folder=args.folder)
        print(json.dumps({"status": "success", "path": result_path}, ensure_ascii=False))
    else:
        parser.print_help()
